#!/usr/bin/env node

const cp = require('child_process');
const fs = require('fs');
const path = require('path');
const format = require('./format-lines');

function getVersion (path) {
  try {
    return fs
      .readFileSync(path, 'utf8')
      .match(/\/\/ OpenZeppelin Contracts \(last updated v[^)]+\)/)[0];
  } catch (err) {
    return null;
  }
}

for (const [ file, template ] of Object.entries({
  'utils/Checkpoints.sol': './templates/Checkpoints.js',
  'mocks/CheckpointsMock.sol': './templates/CheckpointsMock.js',
  'utils/math/SafeCast.sol': './templates/SafeCast.js',
  'mocks/SafeCastMock.sol': './templates/SafeCastMock.js',
})) {
  const script = process.env._;
  const input = path.join(path.dirname(script), template);
  const output = `./contracts/${file}`;
  const version = getVersion(output);
  const content = format(
    '// SPDX-License-Identifier: MIT',
    `// This file was procedurally generated by \`${script}\` from the template file \`${input}\`.`,
    (version ? version + ` (${file})\n` : ''),
    require(template),
  );

  fs.writeFileSync(output, content);
  cp.execFileSync('prettier', ['--write', output]);
}
