#!/usr/bin/env node

const cp = require('child_process');
const fs = require('fs');
const path = require('path');
const format = require('./format-lines');

function getVersion (path) {
  try {
    return fs
      .readFileSync(path, 'utf8')
      .match(/\/\/ OpenZeppelin Contracts \(last updated v[^)]+\)/)[0];
  } catch (err) {
    return null;
  }
}

for (const [ file, template ] of Object.entries({
  'utils/Checkpoints.sol': './templates/Checkpoints',
  'mocks/CheckpointsMock.sol': './templates/CheckpointsMock',
  'utils/math/SafeCast.sol': './templates/SafeCast',
  'mocks/SafeCastMock.sol': './templates/SafeCastMock',
})) {
  const output = `./contracts/${file}`;
  const version = getVersion(output);
  const content = format(
    '// SPDX-License-Identifier: MIT',
    `// This file was procedurally generated by \`${process.env._}\`. Any changes should be performed in the template file \`${path.join(path.dirname(process.env._), template)}\`.`,
    (version ? version + ` (${file})\n` : ''),
    require(template).trimEnd(),
  );

  fs.writeFileSync(output, content);
  cp.execFileSync('prettier', ['--write', output]);
}
