[profile.default]
etherscan_api_key = "${ETHERSCAN_API_KEY}"
ETH_RPC_URL = "https://polygon-rpc.com/"
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]

remappings = [
	"@openzeppelin/contracts/=../contracts/",
]

[rpc_endpoints]
bsctest = "https://bsc-testnet-dataseed.bnbchain.org/"
amoy = "https://rpc-amoy.polygon.technology/"
polygon = "https://polygon-rpc.com/"