name: Setup
description: Common environment setup
inputs:
  use-node:
    description: Whether to set up node
    required: false
    default: 'true'
  node-version:
    description: Version of node to install (if use-node is true)
    required: false
    default: '24.x'
  use-foundry:
    description: Whether to set up Foundry
    required: false
    default: 'true'
  foundry-version:
    description: Version of Foundry to install (if use-foundry is true)
    required: false
    default: 'stable'
  use-java:
    description: Whether to set up Java
    required: false
    default: 'false'
  java-version:
    description: Version of Java to install (if use-java is true)
    required: false
    default: '21'
  use-python:
    description: Whether to set up Python
    required: false
    default: 'false'
  python-version:
    description: Version of Python to install (if use-python is true)
    required: false
    default: '3.13'
  python-requirements:
    description: Path to Python requirements file (if use-python is true)
    required: false
    default: 'requirements.txt'
  use-solc:
    description: Whether to set up solc
    required: false
    default: 'false'
  solc-version:
    description: Version of solc to install (if use-solc is true)
    required: false
    default: '0.8.27'

runs:
  using: composite
  steps:
    # Node & npm setup
    - name: Install Node (${{ inputs.node-version }})
      if: inputs.use-node == 'true'
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
    - name: Try fetch node modules from cache
      id: cache
      if: inputs.use-node == 'true'
      uses: actions/cache@v5
      with:
        path: '**/node_modules'
        key: npm-${{ inputs.node-version }}-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: inputs.use-node == 'true' && steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: npm ci
    # Foundry setup
    - name: Install Foundry (${{ inputs.foundry-version }})
      if: inputs.use-foundry == 'true'
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: ${{ inputs.foundry-version }}
    # Java setup
    - name: Install java (${{ inputs.java-version }})
      if: ${{ inputs.use-java == 'true' }}
      uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: ${{ inputs.java-version }}
    # Python setup
    - name: Install python (${{ inputs.python-version }})
      if: inputs.use-python == 'true'
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'
        cache-dependency-path: ${{ inputs.python-requirements }}
    - name: Install python packages
      if: inputs.use-python == 'true'
      shell: bash
      run: pip install -r ${{ inputs.python-requirements }}
    # Solc setup
    - name: Install solc (${{ inputs.solc-version }})
      if: inputs.use-solc == 'true'
      shell: bash
      run: |
        wget -q https://github.com/argotorg/solidity/releases/download/v${{ inputs.solc-version }}/solc-static-linux
        chmod +x solc-static-linux
        sudo mv solc-static-linux /usr/local/bin/solc
