module.exports = [
  {
    rules: {
      'compatible-pragma': 'error',
      curly: 'off',
      'explicit-types': 'error',
      'id-denylist': 'error',
      'imports-on-top': 'error',
      'max-state-vars': 'error',
      'named-return-params': 'error',
      'naming-convention': 'off',
      'no-console': 'error',
      'no-default-visibility': 'off',
      'no-duplicate-imports': 'error',
      'no-empty-blocks': 'off',
      'no-global-imports': 'error',
      'no-restricted-syntax': 'off',
      'no-send': 'error',
      'no-tx-origin': 'error',
      'no-unchecked-calls': 'error',
      'no-uninitialized-immutable-references': 'error',
      'no-unused-vars': 'error',
      'one-contract-per-file': 'off',
      'private-vars': 'off',
      'require-revert-reason': 'off',
      'sort-imports': 'off',
      'sort-members': 'off',
      'sort-modifiers': 'error',
    },
  },
  {
    ignores: ['contracts/mocks/**/*', 'test/**/*'],
    rules: {
      'no-default-visibility': 'error',
      'private-vars': 'error',
      'require-revert-reason': 'error',
    },
  },
];
