= Account Abstraction

Unlike Externally Owned Accounts (EOAs), smart contracts may contain arbitrary verification logic based on authentication mechanisms different to Ethereum's native xref:api:utils.adoc#ECDSA[ECDSA] and have execution advantages such as batching or gas sponsorship. To leverage these properties of smart contracts, the community has widely adopted https://eips.ethereum.org/EIPS/eip-4337[ERC-4337], a standard to process user operations through an alternative mempool.

OpenZeppelin Contracts provides multiple contracts for Account Abstraction following this standard as it enables more flexible and user-friendly interactions with applications. Account Abstraction use cases include wallets in novel contexts (e.g. embedded wallets), more granular configuration of accounts, recovery mechanisms and modularity with standards such as xref:erc7579.adoc#ERC7579[ERC-7579].

== ERC-4337 Overview

The ERC-4337 is a detailed specification of how to implement the necessary logic to handle operations without making changes to the protocol level (i.e. the rules of the blockchain itself). This specification defines the following components:

=== UserOperation

An `UserOperation` is a higher-layer pseudo-transaction object that represents the intent of the account. This shares some similarities with regular EVM transactions like the concept of `gasFees` or `callData` but includes fields that enable new capabilities.

```solidity
struct PackedUserOperation {
    address sender;
    uint256 nonce;
    bytes initCode; // concatenation of factory address and factoryData (or empty)
    bytes callData;
    bytes32 accountGasLimits; // concatenation of verificationGas (16 bytes) and callGas (16 bytes)
    uint256 preVerificationGas;
    bytes32 gasFees; // concatenation of maxPriorityFee (16 bytes) and maxFeePerGas (16 bytes)
    bytes paymasterAndData; // concatenation of paymaster fields (or empty)
    bytes signature;
}
```

=== Entrypoint

Each `UserOperation` is executed through a contract known as the https://etherscan.io/address/0x0000000071727de22e5e9d8baf0edac6f37da032#code[`EntryPoint`]. This contract is a singleton deployed across multiple networks at the same address although other custom implementations may be used.

The Entrypoint contracts is considered a trusted entity by the account.

=== Bundlers

The bundler is a piece of _offchain_ infrastructure that is in charge of processing an alternative mempool of user operations. Bundlers themselves call the Entrypoint contract's `handleOps` function with an array of UserOperations that are executed and included in a block.

During the process, the bundler pays for the gas of executing the transaction and gets refunded during the execution phase of the Entrypoint contract.

=== Account Contract

The Account Contract is a type of smart contract implements the logic required to validate an `UserOperation` in the context of ERC-4337. Any smart contract account should conform with the `IAccount` interface to validate operations.

```solidity
interface IAccount {
    function validateUserOp(PackedUserOperation calldata, bytes32, uint256) external returns (uint256 validationData);
}
```

Similarly, an Account should have a way to execute these operations by either handling arbitrary calldata on its `fallback` or implementing the `IAccountExecute` interface:

```solidity
interface IAccountExecute {
    function executeUserOp(PackedUserOperation calldata userOp, bytes32 userOpHash) external;
}
```

To build your own account, see xref:account-abstraction.adoc#smart_accounts[Smart Accounts].

=== Factory Contract

The smart contract accounts are created by a Factory contract defined by the Account developer. This factory receives arbitrary bytes as `initData` and returns an `address` where the logic of the account is deployed.

To build your own factory, see xref:account-abstraction.adoc#account_factory[Account Factory]

=== Paymaster Contract

A Paymaster is an optional entity that can sponsor gas fees for Accounts, or allow them to pay for those fees in ERC-20 instead of native currency. This abstracts gas away of the user experience in the same way that computational costs of cloud servers are abstracted away from end-users.

To build your own paymaster, see xref:account-abstraction.adoc#paymaster[Paymaster].

== Smart Accounts

OpenZeppelin provides an abstract implementation of an xref:api:account.adoc#AccountBase[`AccountBase`] that implements both interfaces and accepts native currency and common tokens (i.e. xref:erc20.adoc[ERC-20], xref:erc721.adoc[ERC-721] and xref:erc1155.adoc[ERC-1155]), as well as validating any arbitrary `UserOperation`.

Since developers should implement xref:api:account.adoc#AccountBase-validateUserOp-struct-PackedUserOperation-bytes32-uint256-[`_validateUserOp`] to use the account, the library provides 2 mechanisms to validate user operations. The user should select one of these to build an account.

- **Modules**: An account that is controlled by validator and executor modules.
- **Signers**: An account that is controlled by a private key.

NOTE: Examples provided are simple version of accounts. When using with ERC-4337 infrastructure, a few adjustments are required to make the contract initializable and deployable by a factory. See the xref:account-abstraction.adoc#account_factory[account factory section] for more.

An smart account can be created by deriving from the xref:api:account.adoc#AccountBase[`AccountBase`]:

```solidity
```

NOTE: Using xref:api:utils.adoc#MessageHashUtils-toEthSignedMessageHash-bytes32-[`MessageHashUtils.toEthSignedMessageHash`] wraps the message with an `\x19Ethereum Signed Message:\n` prefix as most wallets do. However, this is not the most recommended approach since it requires the private key owner to sign an opaque message without contextual information. See xref:account-abstraction.adoc#readable_typed_signatures[readable typed signatures].

==== ERC-7562 Validation Rules

To process a bundle of `UserOperations`, bundlers call xref:api:account.adoc#AccountBase-validateUserOp-struct-PackedUserOperation-bytes32-uint256-[`validateUserOp`] on each operation sender to check whether the operation can be executed. However, the bundler has no guarantee that the state of the blockchain will remain the same after the validation phase. To overcome this problematic, https://eips.ethereum.org/EIPS/eip-7562[ERC-7562] proposes a set of limitations to EVM code so that bundlers (or node operators) are protected from unexpected state changes.

These rules outline the requirements for operations to be processed by the canonical mempool.

TIP: Although any Account that breaks such rules may still be processed by a private bundler, developers should keep in mind the centralization tradeoffs of relying on private infrastructure instead of _permissionless_ execution.

===== A note on upgradeability

xref:upgradeable.adoc[Upgradeable Contracts] might easily violate ERC-7562 storage access rules during the validation phase. For example, when upgradeability is present in a module (i.e. an external validator), the account will need to call the proxy and access the implementation address in storage.

The general recommendation for upgradeable accounts is to use a xref:account-abstraction.adoc#Signer[`Signer`] so that the account accesses its own storage during the validation phase, which is allowed by the ERC-7562 rules and preserves the ability of the account of executing operations permissionlessly.

=== Signers

An Account controlled by a signer is a type of account that depends on a https://en.wikipedia.org/wiki/Digital_signature[digital signature] verification algorithm and is similar to Externally Owned Accounts (EOAs) in that they require a private key signature to authenticate it. These accounts can be used with ERC-4337 infrastructure normally and do not violate xref:account-abstraction.adoc#erc_7562_validation_rules[ERC-7562 Validation Rules] when used to validate signatures externally in their upgradeable version.

Generally speaking, blockchains use the properties of https://en.wikipedia.org/wiki/Digital_signature[digital signatures] to authenticate the sender of each transaction. With this in mind, developers can xref:utilities.adoc#checking_signatures_on_chain[verify signatures on-chain] as a way to authenticate user operations for a given off-chain signer (i.e. a private key).

To setup an account signer, start by inheriting from `AccountSigner` and xref:api:account.adoc#ERC1271TypedSigner[`ERC1271TypedSigner`]:

```solidity
```

As you would note, the Account requires to implement both `_validateUserOp` and `_validateSignature`. These are 2 different functions because xref:api:account.adoc#ERC1271TypedSigner[`ERC1271TypedSigner`] adds a wrapper to the `userOpHash` and any other hash received through the `isValidSignature` function the account exposes. The wrapper makes sure that the signature isn't replayable across different account implementations and that the user saw the types associated to the signed message.

IMPORTANT: Accounts must be deployed via an xref:account-abstraction.adoc#account_factory[account factory].

==== Readable Typed Signatures

A common security practice to prevent user operation https://mirror.xyz/curiousapple.eth/pFqAdW2LiJ-6S4sg_u1z08k4vK6BCJ33LcyXpnNb8yU[replayability across smart contract accounts controlled by the same private key] (i.e. multiple accounts for the same signer) is to link the signature to the `address` and `chainId`. This can be done by asking the user to sign the hash of the user operation along with these values.

The problem with this approach is that the user might be prompted by the wallet provider to sign an https://x.com/howydev/status/1780353754333634738[obfuscated message], which is a phishing vector that may lead to a user losing its assets.

To prevent this, each smart contract signer inherits from xref:api:account#ERC1271TypedSigner[`ERC1271TypedSigner`], a utility that implements a defensive rehashing mechanism based on a https://github.com/frangio/eip712-wrapper-for-eip1271[nested EIP-712 approach] to wrap the signature request in a context where there's clearer information for the end user.

==== Alternative signature schemes

Users may add different signature validation schemes such as xref:api:utils.adoc#P256[`P256`] or xref:api:utils.adoc#RSA[`RSA`] to their accounts in a similar fashion to ECDSA:

```solidity
```

=== Modules

Modules are a way to extend functionality of an smart account. Given the variety of smart account implementations, a common approach has been to enable a system of modules to which accounts can delegate logic. As a result, the community has proposed xref:erc7579.adoc#ERC7579[ERC-7579] as a minimal generalized approach to smart account modules.

OpenZeppelin's xref:api:account.adoc#AccountERC7579[`AccountERC7579`] is an ERC-7579 compliant implementation that works without a signer, and instead, uses a validator module installed on the account. This validator module might be any of the https://erc7579.com/modules[validators developed by the community] or one of the xref:api:account.adoc#validators[validator modules we provide].

To setup a modular Account, start by importing xref:api:account.adoc#AccountERC7579[`AccountERC7579`] and make sure to install a module on its initialization.

```solidity

```

WARNING: An account that doesn't setup a module on deployment will be unusable if there's no other execution method enabled on the account.

==== Using with a signer

A modular account can use a signer too. It just needs to override `_validateUserOp` logic to use the signer as part of the validation phase:

```solidity
```

== Account Factory

Accounts are deployed using an xref:api:account.adoc#AccountFactory[`AccountFactory`] contract, a special contract that creates new accounts during the validation phase of the EntryPoint. 

=== Clones

So far this section has shown how to setup an account as an individual contract. However, given that a single factory will deploy the same account multiple times with different arguments, it's recommended to use the xref:api:utils.adoc#Clones[`Clones`] library to produce minimal cloned versions that are cheap to deploy.

The following example demonstrates this concept with an xref:api:account.adoc#AccountERC7579[`AccountERC7579`]

```solidity
```

TIP: xref:upgradeable.adoc[OpenZeppelin Contracts upgradeable] are initializable out of the box.

NOTE: For upgradeable accounts, you might want to check out the xref:api:proxy.adoc#BeaconProxy[`BeaconProxy`] pattern to have a single implementation contract from which upgradeable clones can be created.

These accounts are xref:api:proxy.adoc#Clones-cloneDeterministicWithImmutableArgs-address-bytes-bytes32-[minimal clones with immutable arguments] that are cheap to deploy.

=== Immutable arguments

Considering that Accounts controlled by a signer might store the verification public key in immutable arguments. Then it's not possible to create clones for these kind of accounts since Clones do not support immutable arguments given these are written within the implementation bytecode.

For these cases, developers can leverage xref:api:proxy.adoc#Clones-cloneDeterministicWithImmutableArgs-address-bytes-bytes32-[clones with immutable arguments] to store the public key in a way that's cheap to access in runtime while maintaining the upgradeability capabilities on the account.

To setup a factory, all you need is a xref:account-abstraction.adoc#clonable_accounts[Clonable Account] and implement the `clone` function of the xref:api:account.adoc#AccountFactory[`AccountFactory`] contract

```solidity
```

== Paymaster

== How to send an UserOperation?
