= Account Abstraction

Unlike Externally Owned Accounts (EOAs), smart contracts may contain arbitrary verification logic based on authentication mechanisms different to Ethereum's native xref:api:utils.adoc#ECDSA[ECDSA] and have execution advantages such as batching or gas sponsorship. To leverage these properties of smart contracts, the community has widely adopted https://eips.ethereum.org/EIPS/eip-4337[ERC-4337], a standard to process user operations through an alternative mempool.

OpenZeppelin Contracts provides multiple contracts for Account Abstraction following this standard as it enables more flexible and user-friendly interactions with applications. Account Abstraction use cases include wallets in novel contexts (e.g. embedded wallets), more granular configuration of accounts, recovery mechanisms and modularity with standards such as xref:erc7579.adoc#ERC7579[ERC-7579].

== ERC-4337 Overview

The ERC-4337 is a detailed specification of how to implement the necessary logic to handle operations without making changes to the protocol level (i.e. the rules of the blockchain itself). This specification defines the following components:

=== UserOperation

An `UserOperation` is a higher-layer pseudo-transaction object that represents the intent of the account. This shares some similarities with regular EVM transactions like the concept of `gasFees` or `callData` but includes fields that enable new capabilities.

```solidity
struct PackedUserOperation {
    address sender;
    uint256 nonce;
    bytes initCode; // concatenation of factory address and factoryData (or empty)
    bytes callData;
    bytes32 accountGasLimits; // concatenation of verificationGas (16 bytes) and callGas (16 bytes)
    uint256 preVerificationGas;
    bytes32 gasFees; // concatenation of maxPriorityFee (16 bytes) and maxFeePerGas (16 bytes)
    bytes paymasterAndData; // concatenation of paymaster fields (or empty)
    bytes signature;
}
```

=== Entrypoint

Each `UserOperation` is executed through a contract known as the https://etherscan.io/address/0x0000000071727de22e5e9d8baf0edac6f37da032#code[`EntryPoint`]. This contract is a singleton deployed across multiple networks at the same address although other custom implementations may be used.

The Entrypoint contracts is considered a trusted entity by the account.

=== Bundlers

The bundler is a piece of _offchain_ infrastructure that is in charge of processing an alternative mempool of user operations. Bundlers themselves call the Entrypoint contract's `handleOps` function with an array of UserOperations that are executed and included in a block.

During the process, the bundler pays for the gas of executing the transaction and gets refunded during the execution phase of the Entrypoint contract.

=== Account Contract

The Account Contract is the implementation logic (i.e. Solidity code) that validates user operations and is defined by the Account developer. 

NOTE: To build your own account, see xref:account-abstraction.adoc#smart_accounts[Smart Accounts].

=== Factory Contract

The smart contract accounts are created by a Factory contract defined by the Account developer. This factory receives arbitrary bytes as `initData` and returns an `address` where the logic of the account is deployed.

NOTE: To build your own factory, see xref:account-abstraction.adoc#account_factory[Account Factory]

=== Paymaster Contract

A Paymaster is an optional entity that can sponsor gas fees for Accounts, or allow them to pay for those fees in ERC-20 instead of native currency. This abstracts gas away of the user experience in the same way that computational costs of cloud servers are abstracted away from end-users.

NOTE: To build your own factory, see xref:account-abstraction.adoc#paymaster[Paymaster].

== Smart Accounts

A Smart Account (or simply xref:api:account.adoc[`Account`]) is a type of smart contract implements the logic required to validate an `UserOperation` in the context of ERC-4337. Any smart contract account should conform with the `IAccount` interface to validate operations.

```solidity
interface IAccount {
    function validateUserOp(PackedUserOperation calldata, bytes32, uint256) external returns (uint256 validationData);
}
```

Similarly, an Account should have a way to execute these operations by either handling arbitrary calldata on its `fallback` or implementing the `IAccountExecute` interface:

```solidity
interface IAccountExecute {
    function executeUserOp(PackedUserOperation calldata userOp, bytes32 userOpHash) external;
}
```

OpenZeppelin provides an abstract implementation of an xref:api:account.adoc#AccountBase[`AccountBase`] that implements both interfaces and accepts native currency and common tokens (i.e. xref:erc20.adoc[ERC-20], xref:erc721.adoc[ERC-721] and xref:erc1155.adoc[ERC-1155]), as well as executing any arbitrary `UserOperation`.

Since developers should implement xref:api:account.adoc#AccountBase-validateUserOp-struct-PackedUserOperation-bytes32-uint256-[`_validateUserOp`] to use the account, the library provides 2 mechanisms to validate user operations. The user should select one of these to build an account.

- **Signers**: An non-upgradeable account that is controlled by a private key and stores its corresponding public key in immutable arguments.
- **Modules**: An account that is controlled by validator and executor modules.

=== Signers

An xref:account.adoc#AccountSigner[`AccountSigner`] is useful to create accounts that are controlled by a https://en.wikipedia.org/wiki/Digital_signature[digital signature] verification algorithm.

Generally speaking, blockchains use the properties of https://en.wikipedia.org/wiki/Digital_signature[digital signatures] to authenticate the sender of each transaction. With this in mind, developers can xref:utilities.adoc#checking_signatures_on_chain[verify signatures on-chain] as a way to authenticate user operations for a given off-chain signer (i.e. a private key).

To setup an account signer, start by inheriting from `AccountSigner` and an xref:api:account.adoc#EIP712ReadableSigner[`EIP712ReadableSigner`]:

```solidity
// contracts/MyAccountECDSA.sol
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import {AccountSigner} from "./AccountSigner.sol";
import {EIP712ReadableSigner} from "./EIP712ReadableSigner.sol";
import {SignerECDSA} from "./SignerECDSA.sol";

contract MyAccountECDSA is AccountSigner, SignerECDSA {
    constructor(address signerAddr, string memory name, string memory version) EIP712ReadableSigner(name, version) {}

    /// ...
}
```

IMPORTANT: Accounts must be deployed via an xref:api:account.adoc#AccountFactory[`AccountFactory`] instead of deployed directly. Deploying the account directly will leave it unusable.

==== ERC-7562 Validation Rules

A naive approach to implement an AccountSigner would be to store its public key in the account's storage for future validation and, ideally, expose the xref:api:interfaces::IERC1271[`IERC1271`] interface (smart contract signatures) to act as a validator in more complex setups (e.g. a multisignature). 

However, the validation phase of ERC-4337 forbids access to external storage according to the https://eips.ethereum.org/EIPS/eip-7562[ERC-7562] validation rules. Unfortunately, this rules limit the interoperability of signer contracts unless the public key is stored somewhere other than storage.

For this reason, each AccountSigner contract store the public key for its corresponding validation algorithm in immutable arguments so that the contract is tied to the signer and can validate messages on-chain without accessing storage. Unfortunately, AccountSigners are not upgradeable

==== Readable Typed Signatures

A common security practice to prevent user operation https://mirror.xyz/curiousapple.eth/pFqAdW2LiJ-6S4sg_u1z08k4vK6BCJ33LcyXpnNb8yU[replayability across smart contract accounts controlled by the same private key] (i.e. multiple accounts for the same signer) is to link the signature to the `address` and `chainId`. This can be done by asking the user to sign the hash of the user operation along with these values.

The problem with this approach is that the user might be prompted by the wallet provider to sign an https://x.com/howydev/status/1780353754333634738[obfuscated message], which is a phishing vector that may lead to a user losing its assets.

To prevent this, each smart contract signer inherits from xref:api:account#EIP712ReadableSigner[`EIP712ReadableSigner`], a utility that implements a defensive rehashing mechanism based on a https://github.com/frangio/eip712-wrapper-for-eip1271[nested EIP-712 approach] to wrap the signature request in a context where there's clearer information for the end user.

=== Modules

Modules are a way to extend functionality of an smart account. Given the variety of smart account implementations, a common approach has been to enable a system of modules to which accounts can delegate logic. As a result, the community has proposed xref:erc7579.adoc#ERC7579[ERC-7579] as a minimal generalized approach to smart account modules.

OpenZeppelin's xref:api:account.adoc#AccountERC7579[`AccountERC7579`] is an ERC-7579 compliant implementation that works without a signer, and instead, requires a validator module to be enabled on the account. This validator module might be any of the https://erc7579.com/modules[validators developed by the community].

To setup a modular Account, start by importing xref:api:account.adoc#AccountERC7579[`AccountERC7579`]:

```solidity
// contracts/MyModularAccount.sol
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import {AccountERC7579} from "./AccountERC7579.sol";

contract MyModularAccount is AccountERC7579 {
    /// ...
}
```

WARNING: The AccountERC7579 

== Account Factory

Accounts are deployed using an xref:api:account.adoc#AccountFactory[`AccountFactory`] contract, a special contract that creates new accounts during the validation phase of the EntryPoint. These accounts are xref:api:proxy.adoc#Clones-cloneDeterministicWithImmutableArgs-address-bytes-bytes32-[minimal clones with immutable arguments] that are cheap to deploy.

=== Setting up a factory

To setup a factory, all you need is a xref:account-abstraction.adoc#clonable_accounts[Clonable Account] and implement the `clone` function of the xref:api:account.adoc#AccountFactory[`AccountFactory`] contract

```solidity
// contracts/MyAccountFactory.sol
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import {AccountFactory} from "@openzeppelin/contracts/account/AccountFactory.sol";
import {MyAccountClonableImplementation} from "./MyAccountClonableImplementation.sol";

contract MyAccountFactory is AccountFactory {
    constructor() AccountFactory(address(new MyAccountClonableImplementation())) {}

    function clone(bytes memory encodedSigner, bytes32 salt) external override returns (address) {
        return _clone(encodedSigner, salt);
    }
}
```

== Paymaster
