= ERC-7579

The https://eips.ethereum.org/EIPS/eip-7579[ERC-7579] is a proposal for standardizing smart accounts and modules to ensure interoperability across implementations. The standard defines a set of interfaces for smart acconts that enable developers to delegate logic to third-party smart contracts (or modules). Modules are categorized in the following 4 types:

- **Validators**: Modules to which the smart account delegates the validation of an `UserOperation`.
- **Executors**: Contracts that are allowed to execute calls on behalf of the smart account.
- **Fallback Handler**: A module that extends the https://docs.soliditylang.org/en/latest/contracts.html#fallback-function[fallback function] of a smart account.
- **Hooks**: Contracts that receive a call before and after the execution of a smart account.

OpenZeppelin provides an implementation of an xref:api:account.adoc#ERC7579Account[`ERC7579Account`] that extends from our xref:api:account.adoc#ERC7579Account[`AccountBase`] contract and is compliant with this standard. The account includes support for single or batched calls as well as `delegatecall`. As for modules, it supports installing _Validators_, _Executors_ and _Fallback Handlers_.

== Setting up an ERC-7579 Account
