= Contracts

*A library for secure smart contract development.* Build on a solid foundation of community-vetted code.

 * Implementations of standards like xref:erc20.adoc[ERC20] and xref:erc721.adoc[ERC721].
 * Flexible xref:access-control.adoc[role-based permissioning] scheme.
 * Reusable xref:utilities.adoc[Solidity components] to build custom contracts and complex decentralized systems.

IMPORTANT: OpenZeppelin Contracts uses semantic versioning to communicate backwards compatibility of its API and storage layout. For upgradeable contracts, the storage layout of different major versions should be assumed incompatible, for example, it is unsafe to upgrade from 4.9.3 to 5.0.0. Learn more at xref:backwards-compatibility.adoc[Backwards Compatibility].

== Overview

[[release-tags]]
=== Release Tags

We use NPM tags to clearly distinguish between audited and non-audited versions of our package:

[%header,cols=3*]
|===
| *Tag*
| *Purpose*
| *Description*

| *latest*
| ✅ Audited releases
| Stable, audited versions of the package. This is the *default* version installed when users run `npm install @openzeppelin/contracts`.

| *dev*
| 🧪 Final but not audited
| Versions that are finalized and feature-complete but have *not yet been audited*. This version is fully tested, can be used in production and is covered by the bug bounty.

| *next*
| 🚧 Release candidates
| Pre-release versions that are *not final*. Used for testing and validation before the version becomes a final `dev` or `latest` release.
|===

[[install]]
=== Installation

==== Hardhat (npm)

```console
$ npm install @openzeppelin/contracts
```
→ Installs the latest audited release (`latest`).

```
$ npm install @openzeppelin/contracts@dev
```
→ Installs the latest unaudited release (`dev`).

==== Foundry (git)

WARNING: When installing via git, it is a common error to use the `master` branch. This is a development branch that should be avoided in favor of tagged releases. The release process involves security measures that the `master` branch does not guarantee.

WARNING: Foundry installs the latest version initially, but subsequent `forge update` commands will use the `master` branch.

```console
$ forge install OpenZeppelin/openzeppelin-contracts
```

Add `@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/` in `remappings.txt.` 

[[usage]]
=== Usage

Once installed, you can use the contracts in the library by importing them:

[source,solidity]
----
include::api:example$MyNFT.sol[]
----

TIP: If you're new to smart contract development, head to xref:learn::developing-smart-contracts.adoc[Developing Smart Contracts] to learn about creating a new project and compiling your contracts.

To keep your system secure, you should **always** use the installed code as-is, and neither copy-paste it from online sources, nor modify it yourself. The library is designed so that only the contracts and functions you use are deployed, so you don't need to worry about it needlessly increasing gas costs.

[[security]]
== Security

Please report any security issues you find via our https://www.immunefi.com/bounty/openzeppelin[bug bounty program on Immunefi] or directly to security@openzeppelin.org.

The https://contracts.openzeppelin.com/security[Security Center] contains more details about the secure development process.

[[next-steps]]
== Learn More

The guides in the sidebar will teach about different concepts, and how to use the related contracts that OpenZeppelin Contracts provides:

* xref:access-control.adoc[Access Control]: decide who can perform each of the actions on your system.
* xref:tokens.adoc[Tokens]: create tradable assets or collectibles, like the well known xref:erc20.adoc[ERC20] and xref:erc721.adoc[ERC721] standards.
* xref:utilities.adoc[Utilities]: generic useful tools, including non-overflowing math, signature verification, and trustless paying systems.

The xref:api:token/ERC20.adoc[full API] is also thoroughly documented, and serves as a great reference when developing your smart contract application. You can also ask for help or follow Contracts' development in the https://forum.openzeppelin.com[community forum].

The following articles provide great background reading, though please note, some of the referenced tools have changed as the tooling in the ecosystem continues to rapidly evolve.

* https://blog.openzeppelin.com/the-hitchhikers-guide-to-smart-contracts-in-ethereum-848f08001f05[The Hitchhiker’s Guide to Smart Contracts in Ethereum] will help you get an overview of the various tools available for smart contract development, and help you set up your environment.
* https://blog.openzeppelin.com/a-gentle-introduction-to-ethereum-programming-part-1-783cc7796094[A Gentle Introduction to Ethereum Programming, Part 1] provides very useful information on an introductory level, including many basic concepts from the Ethereum platform.
* For a more in-depth dive, you may read the guide https://blog.openzeppelin.com/designing-the-architecture-for-your-ethereum-application-9cec086f8317[Designing the architecture for your Ethereum application], which discusses how to better structure your application and its relationship to the real world.
