= Account
[.readme-notice]
NOTE: This document is better viewed at https://docs.openzeppelin.com/contracts/api/account

This directory includes contracts to build accounts for ERC-4337. These include:

 * {Account}: An ERC-4337 smart account implementation that includes the core logic to process user operations.
 * {AccountERC7579}: An extension of `Account` that implements support for ERC-7579 modules.
 * {AccountERC7579Hooked}: An extension of `AccountERC7579` with support for a single hook module (type 4).
 * {ERC7579Executor}: An executor module that enables executing calls from accounts where the it's installed.
 * {ERC7579DelayedExecutor}: An executor module that adds a delay before executing an account operation.
 * {ERC7579Validator}: Abstract validator module for ERC-7579 accounts that provides base implementation for signature validation.
 * {ERC7579Signature}: Implementation of {ERC7579Validator} using ERC-7913 signature verification for address-less cryptographic keys and account signatures.
 * {ERC7579Multisig}: An extension of {ERC7579Validator} that enables validation using ERC-7913 signer keys.
 * {ERC7579MultisigWeighted}: An extension of {ERC7579Multisig} that allows different weights to be assigned to signers.
 * {ERC7821}: Minimal batch executor implementation contracts. Useful to enable easy batch execution for smart contracts.
 * {ERC4337Utils}: Utility functions for working with ERC-4337 user operations.
 * {ERC7579Utils}: Utility functions for working with ERC-7579 modules and account modularity.

== Core

{{Account}}

== Extensions

{{AccountERC7579}}

{{AccountERC7579Hooked}}

{{ERC7821}}

== Modules

=== Executors

{{ERC7579Executor}}

{{ERC7579DelayedExecutor}}

=== Validators

{{ERC7579Validator}}

{{ERC7579Signature}}

{{ERC7579Multisig}}

{{ERC7579MultisigWeighted}}

== Utilities

{{ERC4337Utils}}

{{ERC7579Utils}}
