name: lint workflows

on:
  pull_request:
    paths:
      - '.github/**/*.ya?ml'

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Add problem matchers
        run: |
          # https://github.com/rhysd/actionlint/blob/3a2f2c7/docs/usage.md#problem-matchers
          curl -LO https://raw.githubusercontent.com/rhysd/actionlint/main/.github/actionlint-matcher.json
          echo "::add-matcher::actionlint-matcher.json"
      - uses: docker://rhysd/actionlint:latest@sha256:1d74bfc9fd1963af8f89a7c22afaaafd42f49aad711a09951d02cb996398f61d
