name: Transpile upgradeable

on:
  push:
    branches:
      - master
      - release-v*

jobs:
  transpile:
    environment: push-upgradeable
    permissions:
      contents: read
    if: ${{ !endsWith(github.repository, '-upgradeable') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          repository: ${{ github.repository }}-upgradeable
          fetch-depth: 0
          persist-credentials: false
      - name: Fetch current non-upgradeable branch
        run: |
          git fetch "$REMOTE" master # Fetch default branch first for patch to apply cleanly
          git fetch "$REMOTE" "$REF"
          git checkout FETCH_HEAD
        env:
          REF: ${{ github.ref }}
          REMOTE: https://github.com/${{ github.repository }}.git
      - name: Set up environment
        uses: ./.github/actions/setup
      - run: bash scripts/git-user-config.sh
      - name: Transpile to upgradeable
        run: bash scripts/upgradeable/transpile-onto.sh "$REF_NAME" "origin/$REF_NAME"
        env:
          REF_NAME: ${{ github.ref_name }}
          SUBMODULE_REMOTE: https://github.com/${{ github.repository }}.git
      - name: Push to upgradeable
        run: git push "https://x-access-token:${GH_TOKEN}@github.com/${REPOSITORY}-upgradeable.git" -- "$REF_NAME"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_UPGRADEABLE }}
          REF_NAME: ${{ github.ref_name }}
          REPOSITORY: ${{ github.repository }}
